### ISSUE TITLE
Running without arguments fails

### ISSUE THREAD

**Issue by r-barnes** [ybayle/Scyland3D#1]
Configuration shows a command-line entry point
```
    entry_points='''
        [console_scripts]
        Scyland3D=Scyland3D:pts2csv
    ''',
```

Running `Scyland3D` on the command line raises an error:
```
rick@sally:/z$ Scyland3D 
Traceback (most recent call last):
  File "/home/rick/.local/bin/Scyland3D", line 11, in <module>
    sys.exit(pts2csv())
TypeError: pts2csv() missing 1 required positional argument: 'indir'
```

**Comment by r-barnes** [comment]
It seems us that the program is adapted only for use within the Python environment, despite having this command line functionality. I suggest that you flesh out the command line functionality using the argparse package. This is likely to expand the scope of users that can benefit from your work.

**Comment by ybayle** [comment]
Thanks for this suggestion. The arg parsing is now possible.

**Comment by r-barnes** [comment]
The program doesn't run from the CLI. It fails with the warning:
```
Traceback (most recent call last):
  File "/home/rick/.local/bin/Scyland3D", line 7, in <module>
    from Scyland3D import main
ImportError: cannot import name 'main'
```

When run without arguments, my expectation is that the program will offer help:
```
python3 ./Scyland3D/Scyland3D.py
```
However, it instead processes a directory of example files. This is not helpful.

Consider [`argparse`](https://docs.python.org/3/library/argparse.html) as a more Pythonic way of parsing arguments, as suggested in the original review comment.

**Comment by r-barnes** [comment]
Looks good.
