### ISSUE TITLE
Comments in code

### ISSUE THREAD

**Issue by r-barnes** [ybayle/Scyland3D#8]
The source code tells the computer what to do, but does not explain what you intended the computer to do. Given the speed with which the open-source world changes, and the lack of incentives to maintain software with academia, I think it's valuable to have comments within code so that people providing patches, new features, or updating the code have an easy way of orientating themselves to the intended functionality of what can otherwise be mysterious code blocks.

Please add additional comments within the code.

**Comment by ybayle** [comment]
Additional comments and description were added to the code. Tell me if some part of code deserve more description, thanks.

**Comment by r-barnes** [comment]
This issue seems almost entirely unaddressed. Please comment your code.

**Comment by r-barnes** [comment]
The docstrings are an excellent addition. However, certain parts of the code are still mysterious.

For instance, what does this equation

    t = float((D - A * x - B * y - C * z) / (A * A + B * B + C * C))

do?

A more liberal use of comments within the source itself will make it easier for you and others to modify the code later.

**Comment by ybayle** [comment]
I pushed a new commit that enhance the degree of verbosity of the comments in the code in answer to this issue and to the comments detailed here: https://github.com/ybayle/Scyland3D/commit/c75e13cb0f372a9a5a271931fbc0624d942435b9#comments
Could you confirm that this issue is solved?

**Comment by patrikhuber** [comment]
a01a14f2657134fd2ae7a91cc9fa9bf3e04a906b improved the readability / understanding of the code a lot! 👍 

It would probably be good to hear @r-barnes's comment about it but I have no further comments.

**Comment by ybayle** [comment]
Ok thanks!

**Comment by r-barnes** [comment]
It is much better.

Random aside. [This line](https://github.com/ybayle/Scyland3D/blob/a01a14f2657134fd2ae7a91cc9fa9bf3e04a906b/Scyland3D/Scyland3D.py#L304) _might_ be simplified through the use of regular expressions, but I'm not sure.
