### ISSUE TITLE
CSV output

### ISSUE THREAD

**Issue by r-barnes** [ybayle/Scyland3D#9]
The `export2csv()` and `write_header()` functions make me nervous because they have a lot of handwritten code, which seems unnecessary because python has a core CSV module that seems as though it could handle much of this. Is it possible to make use of this module to simplify the code?

**Comment by ybayle** [comment]
Thanks for your advice, the code has been refactored to use the core python csv module. If the modifications seem satisfactory, please close the issue.

**Comment by r-barnes** [comment]
I'm very confused by this:
```
    for numb in range(1, nb_landmark + 1):
        [fieldnames.append(axe + str(numb)) for axe in ["x", "y", "z"]]
```
Why are you creating and throwing away a list on each iteration of the for loop?

(Similar issues appear elsewhere.)

**Comment by ybayle** [comment]
Thanks for your advice, the code has been refactored to avoid this and to be clearer in the version 1.0.3. If the modifications seem satisfactory, please close the issue.
